repos:
  # Lint first (with safe autofixes)
  # Fast formatter (optional alongside Black)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.0
    hooks:
      - id: ruff-format
        name: ruff-format
        types_or: [python]
  # Strip notebook outputs anywhere in repo
  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout
        types: [jupyter]

exclude: |
  (?x)(
    ^\.git/|
    ^\.venv/|^venv/|
    ^\.pytest_cache/|^\.mypy_cache/|
    ^\.ipynb_checkpoints/
  )
