FROM quay.io/sclorg/python-311-c9s:c9s

USER 0

RUN cat /etc/redhat-release

RUN dnf -y install --best --nodocs --setopt=install_weak_deps=False dnf-plugins-core && \
    dnf config-manager --best --nodocs --setopt=install_weak_deps=False --save && \
    dnf config-manager --enable crb && \
    dnf -y update && \
    dnf -y install tesseract tesseract-devel tesseract-langpack-eng tesseract-osd leptonica-devel libglvnd-glx glib2 && \
    dnf -y clean all && \
    rm -rf /var/cache/dnf

RUN /usr/bin/fix-permissions /opt/app-root/src/.cache

ENV TESSDATA_PREFIX=/usr/share/tesseract/tessdata/

USER 1001

WORKDIR /opt/app-root/src

ENV OMP_NUM_THREADS=4 \
    PYTHONIOENCODING=UTF-8 \
    LC_ALL=en_US.UTF-8 \
    LANG=en_US.UTF-8 \
    PIP_NO_CACHE_DIR=1 \
    HOME=/opt/app-root/src \
    PATH=/opt/app-root/src:$PATH \
    DOCLING_ARTIFACTS_PATH=/opt/app-root/src/.cache/docling/models

# This will install torch with *only* cpu support
# Remove the --extra-index-url part if you want to install all the gpu requirements
# For more details in the different torch distribution visit https://pytorch.org/.
RUN pip install --no-cache-dir docling --extra-index-url https://download.pytorch.org/whl/cpu && \
    pip uninstall -y tesserocr && \
    pip install --no-cache-dir --no-binary :all: tesserocr && \
    chmod -R g+w /opt/app-root/lib/python3.11/site-packages && \
    chmod -R g+w /opt/app-root/lib64/python3.11/site-packages && \
    fix-permissions /opt/app-root -P

ENV HF_HOME=/tmp/
ENV TORCH_HOME=/tmp/

RUN docling --version

RUN echo "Downloading models..." && \
    docling-tools models download layout tableformer -o "${DOCLING_ARTIFACTS_PATH}"

# Running with `DOCLING_ARTIFACTS_PATH=/opt/app-root/src/.cache/docling/models` will use the
# models included in the container image.
