FROM quay.io/modh/odh-workbench-jupyter-minimal-cuda-py312-ubi9@sha256:f7126e237f1dfe3a4cda89b60c4e8d9e45afabb247030765edb1c5532a7010fc

# If an image with cuda is not required
#FROM quay.io/modh/odh-workbench-jupyter-minimal-cpu-py312-ubi9@sha256:9a8f2ce61e465267deb4d9a7662e6839c36969f4e5d1674a19c85c7728a8a528

USER 1001

# Clone the repository to a temporary, non-mounted directory
RUN git clone https://github.com/opendatahub-io/odh-data-processing.git /opt/app-root/tmp/odh-data-processing

# Copy a custom entrypoint script into the container
COPY --chown=1001:1 odh-dp-entrypoint.sh /opt/app-root/bin/odh-dp-entrypoint.sh

# Check to make sure entry point script can be executed by random high number user
RUN ls -l /opt/app-root/bin/odh-dp-entrypoint.sh

# Set the NOTEBOOK_ROOT_DIR to the final destination in the user's home directory
ENV NOTEBOOK_ROOT_DIR="/opt/app-root/src/odh-data-processing/notebooks/use-cases"

# Set the custom script as the new entrypoint
ENTRYPOINT ["/opt/app-root/bin/odh-dp-entrypoint.sh"]
